import type { TTSLanguage } from "@/lib/connectors/tts/enums";

/** What a voice says to be heard by, in each language it can speak. */
export const PREVIEW_LINES: Record<TTSLanguage, string> = {
	en: "Hello! This is how my voice sounds. I hope it suits your story.",
	fr: "Bonjour ! Voici à quoi ressemble ma voix. J'espère qu'elle conviendra à votre histoire.",
	de: "Hallo! So klingt meine Stimme. Ich hoffe, sie passt zu Ihrer Geschichte.",
	es: "¡Hola! Así suena mi voz. Espero que encaje con tu historia.",
	pt: "Olá! É assim que a minha voz soa. Espero que combine com a sua história.",
	zh: "你好！这就是我的声音。希望它适合你的故事。",
	ja: "こんにちは！これが私の声です。あなたの物語に合うといいなと思います。",
	hi: "नमस्ते! मेरी आवाज़ ऐसी सुनाई देती है। मुझे उम्मीद है कि यह आपकी कहानी के लिए सही होगी।",
	it: "Ciao! Ecco come suona la mia voce. Spero che sia adatta alla tua storia.",
	ko: "안녕하세요! 제 목소리는 이렇게 들립니다. 당신의 이야기에 잘 어울리면 좋겠어요.",
	nl: "Hallo! Zo klinkt mijn stem. Ik hoop dat hij bij je verhaal past.",
	pl: "Cześć! Tak brzmi mój głos. Mam nadzieję, że pasuje do twojej historii.",
	ru: "Привет! Вот так звучит мой голос. Надеюсь, он подойдёт для вашей истории.",
	sv: "Hej! Så här låter min röst. Jag hoppas att den passar din berättelse.",
	tr: "Merhaba! Sesim böyle duyuluyor. Umarım hikâyene uyar.",
	tl: "Kumusta! Ganito ang tunog ng boses ko. Sana bagay ito sa kuwento mo.",
	bg: "Здравейте! Ето как звучи гласът ми. Надявам се да подхожда на вашата история.",
	ro: "Bună! Așa sună vocea mea. Sper să se potrivească poveștii tale.",
	ar: "مرحبًا! هكذا يبدو صوتي. أتمنى أن يناسب قصتك.",
	cs: "Ahoj! Takhle zní můj hlas. Doufám, že se bude hodit k tvému příběhu.",
	el: "Γεια σας! Έτσι ακούγεται η φωνή μου. Ελπίζω να ταιριάζει στην ιστορία σας.",
	fi: "Hei! Tältä ääneni kuulostaa. Toivottavasti se sopii tarinaasi.",
	hr: "Bok! Ovako zvuči moj glas. Nadam se da pristaje tvojoj priči.",
	ms: "Hai! Beginilah bunyi suara saya. Saya harap ia sesuai dengan cerita anda.",
	sk: "Ahoj! Takto znie môj hlas. Dúfam, že sa bude hodiť k tvojmu príbehu.",
	da: "Hej! Sådan lyder min stemme. Jeg håber, den passer til din historie.",
	ta: "வணக்கம்! என் குரல் இப்படித்தான் ஒலிக்கும். இது உங்கள் கதைக்குப் பொருந்தும் என்று நம்புகிறேன்.",
	uk: "Привіт! Ось так звучить мій голос. Сподіваюся, він пасуватиме вашій історії.",
	hu: "Szia! Így szól a hangom. Remélem, illik a történetedhez.",
	no: "Hei! Slik høres stemmen min ut. Jeg håper den passer til historien din.",
	vi: "Xin chào! Đây là giọng nói của tôi. Hy vọng nó phù hợp với câu chuyện của bạn.",
	bn: "হ্যালো! আমার কণ্ঠস্বর এমন শোনায়। আশা করি এটি আপনার গল্পের সাথে মানাবে।",
	th: "สวัสดี! นี่คือเสียงของฉัน หวังว่าจะเข้ากับเรื่องราวของคุณนะ",
	he: "שלום! ככה נשמע הקול שלי. אני מקווה שהוא מתאים לסיפור שלך.",
	ka: "გამარჯობა! ასე ჟღერს ჩემი ხმა. იმედი მაქვს, თქვენს ისტორიას მოერგება.",
	id: "Halo! Beginilah suara saya. Semoga cocok dengan ceritamu.",
	te: "నమస్కారం! నా గొంతు ఇలా వినిపిస్తుంది. ఇది మీ కథకు సరిపోతుందని ఆశిస్తున్నాను.",
	gu: "નમસ્તે! મારો અવાજ આવો સંભળાય છે. મને આશા છે કે તે તમારી વાર્તાને અનુરૂપ હશે.",
	kn: "ನಮಸ್ಕಾರ! ನನ್ನ ಧ್ವನಿ ಹೀಗೆ ಕೇಳಿಸುತ್ತದೆ. ಇದು ನಿಮ್ಮ ಕಥೆಗೆ ಹೊಂದುತ್ತದೆ ಎಂದು ಆಶಿಸುತ್ತೇನೆ.",
	ml: "നമസ്കാരം! എന്റെ ശബ്ദം ഇങ്ങനെയാണ്. ഇത് നിങ്ങളുടെ കഥയ്ക്ക് ചേരുമെന്ന് ഞാൻ പ്രതീക്ഷിക്കുന്നു.",
	mr: "नमस्कार! माझा आवाज असा ऐकू येतो. मला आशा आहे की तो तुमच्या कथेला शोभेल.",
	pa: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੇਰੀ ਆਵਾਜ਼ ਇਸ ਤਰ੍ਹਾਂ ਸੁਣਾਈ ਦਿੰਦੀ ਹੈ। ਮੈਨੂੰ ਉਮੀਦ ਹੈ ਕਿ ਇਹ ਤੁਹਾਡੀ ਕਹਾਣੀ ਦੇ ਅਨੁਕੂਲ ਹੋਵੇਗੀ।",
};
